insert into stores (name, location) values ('Bruen-Graham', 'Fatufaun');
insert into stores (name, location) values ('Bartell-Keeling', 'Mandi Bahāuddīn');
insert into stores (name, location) values ('Jaskolski Group', 'Xinbu');
insert into stores (name, location) values ('Lynch Inc', 'Hadabei');
insert into stores (name, location) values ('Quitzon-O''Reilly', 'Balengbeng');
insert into stores (name, location) values ('Hodkiewicz-Kunde', 'Magatos');
insert into stores (name, location) values ('Cronin, Schuppe and Kozey', 'Rendeng');
insert into stores (name, location) values ('Braun LLC', 'Chisong');
insert into stores (name, location) values ('Hoeger-Ullrich', 'Shuangzhu');
insert into stores (name, location) values ('Stoltenberg Inc', 'Hollola');
insert into stores (name, location) values ('Kohler LLC', 'Örnsköldsvik');
insert into stores (name, location) values ('Murray-Johns', 'Mantingantengah');
insert into stores (name, location) values ('Langworth-Prosacco', 'Tulsa');
insert into stores (name, location) values ('Kassulke Inc', 'Јегуновце');
insert into stores (name, location) values ('Crist, Stark and Wintheiser', 'Tromsø');
insert into stores (name, location) values ('Nicolas, Collier and Rice', 'Taihe Chengguanzhen');
insert into stores (name, location) values ('Runolfsdottir-Willms', 'Priargunsk');
insert into stores (name, location) values ('Miller-Prohaska', 'Tân Sơn');
insert into stores (name, location) values ('Bergnaum, Flatley and Kohler', 'Dortmund');
insert into stores (name, location) values ('Crooks-Prosacco', 'Cilampuyang');
insert into stores (name, location) values ('Schmitt-Swaniawski', 'Nantes');
insert into stores (name, location) values ('Schaden Inc', 'Kayapa');
insert into stores (name, location) values ('Lueilwitz-Corkery', 'Luboń');
insert into stores (name, location) values ('Murazik-Marks', 'Kazinka');
insert into stores (name, location) values ('Jerde-O''Connell', 'Nobres');
insert into stores (name, location) values ('Collins-Harris', 'Thị Trấn Yên Ninh');
insert into stores (name, location) values ('Lindgren and Sons', 'Lovran');
insert into stores (name, location) values ('Spinka Group', 'Strellc i Ulët');
insert into stores (name, location) values ('Auer, Hettinger and Bode', 'El Cortezo');
insert into stores (name, location) values ('Thiel Inc', 'Tomohon');
insert into stores (name, location) values ('Botsford-McKenzie', 'Mulyadadi');
insert into stores (name, location) values ('O''Conner, Bosco and Ruecker', 'Sikasso');
insert into stores (name, location) values ('Ferry Group', 'Tëplaya Gora');
insert into stores (name, location) values ('Conn and Sons', 'Nova Olímpia');
insert into stores (name, location) values ('Rutherford, Rau and Huel', 'Pinega');
insert into stores (name, location) values ('Marks, Kuhlman and Stroman', 'Mombok');
insert into stores (name, location) values ('Beier, Adams and Prosacco', 'Moravský Písek');
insert into stores (name, location) values ('Strosin-Herman', 'Jiangcun');
insert into stores (name, location) values ('Gerhold Inc', 'Tuncheng');
insert into stores (name, location) values ('Volkman-Jones', 'Jankowice');
insert into stores (name, location) values ('Mante-Runolfsson', 'Ribas do Rio Pardo');
insert into stores (name, location) values ('Jacobi-Gerhold', 'Pondokaso');
insert into stores (name, location) values ('Schinner LLC', 'Numan');
insert into stores (name, location) values ('Ledner LLC', 'Metsamor');
insert into stores (name, location) values ('Predovic-Grady', 'Malichang');
insert into stores (name, location) values ('Roob-Kessler', 'San José de Colinas');
insert into stores (name, location) values ('Tromp Inc', 'Legrada');
insert into stores (name, location) values ('Schaefer LLC', 'Waldbillig');
insert into stores (name, location) values ('Frami-Hartmann', 'Sokolnice');
insert into stores (name, location) values ('Conn-Daugherty', 'Lianhe');
insert into stores (name, location) values ('Volkman-Bahringer', 'Xinghua');
insert into stores (name, location) values ('Larkin-Wolff', 'Kogon');
insert into stores (name, location) values ('Lowe LLC', 'Tuanjie');
insert into stores (name, location) values ('Murphy-King', 'Tayabo');
insert into stores (name, location) values ('O''Connell, Conn and McKenzie', 'Lambayong');
insert into stores (name, location) values ('Steuber-Jacobson', 'Karasgede');
insert into stores (name, location) values ('Schroeder-Emard', 'Shanxiahu');
insert into stores (name, location) values ('Miller Group', 'Linköping');
insert into stores (name, location) values ('Goyette-Stehr', 'Byahoml’');
insert into stores (name, location) values ('Labadie-Hermann', 'Nanxinxiang');
insert into stores (name, location) values ('Kessler, Daugherty and Kling', 'Hutang');
insert into stores (name, location) values ('Bosco, Osinski and Collier', 'Xinrong');
insert into stores (name, location) values ('McGlynn Inc', 'Velasco Ibarra');
insert into stores (name, location) values ('Leuschke-Jast', 'Bahāwalpur');
insert into stores (name, location) values ('Jakubowski Inc', 'Lokwabe');
insert into stores (name, location) values ('Schamberger Inc', 'Ropa');
insert into stores (name, location) values ('Romaguera, Bins and Osinski', 'Sendafa');
insert into stores (name, location) values ('Wolff Inc', 'San Nicolas');
insert into stores (name, location) values ('Shields Inc', 'Nankeng');
insert into stores (name, location) values ('Effertz Inc', 'Raduzhnyy');
insert into stores (name, location) values ('Wilderman-MacGyver', 'Bogorodsk');
insert into stores (name, location) values ('Prohaska-Davis', 'Lérida');
insert into stores (name, location) values ('Glover, Predovic and Rau', 'Vidyayevo');
insert into stores (name, location) values ('Johnston and Sons', 'Greensboro');
insert into stores (name, location) values ('Davis Inc', 'Morrinhos');
insert into stores (name, location) values ('Ferry LLC', 'Tintafor');
insert into stores (name, location) values ('White, Cronin and Nader', 'Chicago');
insert into stores (name, location) values ('Parisian-Goodwin', 'Quận Bốn');
insert into stores (name, location) values ('Bernier, Mohr and Bins', 'Pamplona');
insert into stores (name, location) values ('Kessler, Baumbach and Klein', 'Farinheiras');
insert into stores (name, location) values ('Grady Inc', 'Guling');
insert into stores (name, location) values ('Hudson-Greenfelder', 'Mataya');
insert into stores (name, location) values ('Cremin-Champlin', 'Jincang');
insert into stores (name, location) values ('Williamson, Price and Ullrich', 'Tagoloan');
insert into stores (name, location) values ('Larson LLC', 'Kertosari');
insert into stores (name, location) values ('Pfannerstill-Ullrich', 'Tučepi');
insert into stores (name, location) values ('Christiansen, Jerde and Corkery', 'Ziroudani');
insert into stores (name, location) values ('Hegmann-Schuppe', 'Chiquinquirá');
insert into stores (name, location) values ('Hilll, McKenzie and Fay', 'Matou');
insert into stores (name, location) values ('Jast, VonRueden and Bosco', 'Kaesŏng');
insert into stores (name, location) values ('Gottlieb, Wehner and Russel', 'Pretana');
insert into stores (name, location) values ('Gorczany-Collier', 'West End');
insert into stores (name, location) values ('Thiel Group', 'Erping');
insert into stores (name, location) values ('Pfannerstill and Sons', 'Campok');
insert into stores (name, location) values ('Volkman and Sons', 'Amsterdam Westpoort');
insert into stores (name, location) values ('Bayer-Cremin', 'Liuhou');
insert into stores (name, location) values ('Emard, Kassulke and Lebsack', 'Wanjia');
insert into stores (name, location) values ('Heidenreich-Pagac', 'Rathdrum');
insert into stores (name, location) values ('Maggio LLC', 'Phú Vang');
insert into stores (name, location) values ('Mosciski-Terry', 'Nārāyanganj');
