insert into track_num (track_num, order_id, address_to_deliver) values (671939, 83, 'Lotheville');
insert into track_num (track_num, order_id, address_to_deliver) values (100045, 92, 'Hanover');
insert into track_num (track_num, order_id, address_to_deliver) values (552350, 29, 'Texas');
insert into track_num (track_num, order_id, address_to_deliver) values (424650, 74, 'Annamark');
insert into track_num (track_num, order_id, address_to_deliver) values (393667, 42, 'Pleasure');
insert into track_num (track_num, order_id, address_to_deliver) values (343337, 104, 'Clove');
insert into track_num (track_num, order_id, address_to_deliver) values (519857, 1, 'Portage');
insert into track_num (track_num, order_id, address_to_deliver) values (773925, 11, 'Lillian');
insert into track_num (track_num, order_id, address_to_deliver) values (212118, 17, 'Oakridge');
insert into track_num (track_num, order_id, address_to_deliver) values (470963, 34, 'High Crossing');
insert into track_num (track_num, order_id, address_to_deliver) values (373417, 62, 'Crest Line');
insert into track_num (track_num, order_id, address_to_deliver) values (669803, 21, 'Green Ridge');
insert into track_num (track_num, order_id, address_to_deliver) values (846929, 18, 'Granby');
insert into track_num (track_num, order_id, address_to_deliver) values (268968, 92, 'Brickson Park');
insert into track_num (track_num, order_id, address_to_deliver) values (353753, 36, 'Kim');
insert into track_num (track_num, order_id, address_to_deliver) values (728887, 50, 'Farmco');
insert into track_num (track_num, order_id, address_to_deliver) values (294403, 7, 'Rusk');
insert into track_num (track_num, order_id, address_to_deliver) values (103585, 16, 'Spaight');
insert into track_num (track_num, order_id, address_to_deliver) values (475047, 23, 'Stephen');
insert into track_num (track_num, order_id, address_to_deliver) values (865289, 79, 'Oak');
insert into track_num (track_num, order_id, address_to_deliver) values (369629, 9, 'Main');
insert into track_num (track_num, order_id, address_to_deliver) values (736749, 107, 'Cascade');
insert into track_num (track_num, order_id, address_to_deliver) values (396018, 29, 'Sage');
insert into track_num (track_num, order_id, address_to_deliver) values (741113, 30, 'Welch');
insert into track_num (track_num, order_id, address_to_deliver) values (865775, 50, '3rd');
insert into track_num (track_num, order_id, address_to_deliver) values (726543, 72, 'Ryan');
insert into track_num (track_num, order_id, address_to_deliver) values (500778, 16, 'Forest Run');
insert into track_num (track_num, order_id, address_to_deliver) values (818837, 24, 'Sunfield');
insert into track_num (track_num, order_id, address_to_deliver) values (371392, 86, 'American');
insert into track_num (track_num, order_id, address_to_deliver) values (686844, 84, 'Jana');
insert into track_num (track_num, order_id, address_to_deliver) values (433123, 71, 'Village Green');
insert into track_num (track_num, order_id, address_to_deliver) values (887835, 65, 'Sauthoff');
insert into track_num (track_num, order_id, address_to_deliver) values (719652, 30, 'Division');
insert into track_num (track_num, order_id, address_to_deliver) values (351708, 60, 'Swallow');
insert into track_num (track_num, order_id, address_to_deliver) values (270907, 31, 'Milwaukee');
insert into track_num (track_num, order_id, address_to_deliver) values (482559, 83, 'School');
insert into track_num (track_num, order_id, address_to_deliver) values (326879, 30, 'Farwell');
insert into track_num (track_num, order_id, address_to_deliver) values (737168, 72, 'Lake View');
insert into track_num (track_num, order_id, address_to_deliver) values (107242, 63, 'Eastwood');
insert into track_num (track_num, order_id, address_to_deliver) values (698635, 64, '5th');
insert into track_num (track_num, order_id, address_to_deliver) values (797909, 104, 'Jenna');
insert into track_num (track_num, order_id, address_to_deliver) values (294832, 4, 'Mcguire');
insert into track_num (track_num, order_id, address_to_deliver) values (447947, 32, 'Twin Pines');
insert into track_num (track_num, order_id, address_to_deliver) values (685251, 72, 'Brentwood');
insert into track_num (track_num, order_id, address_to_deliver) values (767660, 19, 'Lerdahl');
insert into track_num (track_num, order_id, address_to_deliver) values (398463, 16, 'Arrowood');
insert into track_num (track_num, order_id, address_to_deliver) values (695509, 60, 'Tony');
insert into track_num (track_num, order_id, address_to_deliver) values (640614, 66, 'Knutson');
insert into track_num (track_num, order_id, address_to_deliver) values (894312, 103, 'Leroy');
insert into track_num (track_num, order_id, address_to_deliver) values (325656, 55, 'Memorial');
insert into track_num (track_num, order_id, address_to_deliver) values (643607, 99, '2nd');
insert into track_num (track_num, order_id, address_to_deliver) values (711052, 74, 'Florence');
insert into track_num (track_num, order_id, address_to_deliver) values (797288, 57, 'Declaration');
insert into track_num (track_num, order_id, address_to_deliver) values (779293, 69, 'Graceland');
insert into track_num (track_num, order_id, address_to_deliver) values (682575, 71, 'Holmberg');
insert into track_num (track_num, order_id, address_to_deliver) values (751844, 92, 'Dovetail');
insert into track_num (track_num, order_id, address_to_deliver) values (343409, 20, 'Di Loreto');
insert into track_num (track_num, order_id, address_to_deliver) values (384623, 77, 'Division');
insert into track_num (track_num, order_id, address_to_deliver) values (506981, 42, 'Brickson Park');
insert into track_num (track_num, order_id, address_to_deliver) values (433035, 19, 'Shelley');
insert into track_num (track_num, order_id, address_to_deliver) values (284613, 38, 'Heath');
insert into track_num (track_num, order_id, address_to_deliver) values (138961, 46, 'Anhalt');
insert into track_num (track_num, order_id, address_to_deliver) values (563143, 12, 'Paget');
insert into track_num (track_num, order_id, address_to_deliver) values (864124, 80, 'Memorial');
insert into track_num (track_num, order_id, address_to_deliver) values (487842, 94, 'Utah');
insert into track_num (track_num, order_id, address_to_deliver) values (459963, 38, 'Eliot');
insert into track_num (track_num, order_id, address_to_deliver) values (531831, 22, 'Warbler');
insert into track_num (track_num, order_id, address_to_deliver) values (310737, 49, 'Mccormick');
insert into track_num (track_num, order_id, address_to_deliver) values (478682, 85, 'Lakewood Gardens');
insert into track_num (track_num, order_id, address_to_deliver) values (597224, 40, 'Mayfield');
insert into track_num (track_num, order_id, address_to_deliver) values (334200, 64, 'Redwing');
insert into track_num (track_num, order_id, address_to_deliver) values (142005, 24, 'Montana');
insert into track_num (track_num, order_id, address_to_deliver) values (270052, 37, 'Gulseth');
insert into track_num (track_num, order_id, address_to_deliver) values (671094, 2, 'Drewry');
insert into track_num (track_num, order_id, address_to_deliver) values (657040, 95, 'Chinook');
insert into track_num (track_num, order_id, address_to_deliver) values (571643, 26, 'Ruskin');
insert into track_num (track_num, order_id, address_to_deliver) values (798971, 13, 'Heath');
insert into track_num (track_num, order_id, address_to_deliver) values (744713, 3, 'Beilfuss');
insert into track_num (track_num, order_id, address_to_deliver) values (676862, 102, 'Goodland');
insert into track_num (track_num, order_id, address_to_deliver) values (604956, 28, 'Veith');
insert into track_num (track_num, order_id, address_to_deliver) values (627098, 80, 'Summer Ridge');
insert into track_num (track_num, order_id, address_to_deliver) values (408788, 45, 'Monument');
insert into track_num (track_num, order_id, address_to_deliver) values (226049, 64, 'Brown');
insert into track_num (track_num, order_id, address_to_deliver) values (242858, 36, 'Charing Cross');
insert into track_num (track_num, order_id, address_to_deliver) values (888232, 10, 'Lakewood Gardens');
insert into track_num (track_num, order_id, address_to_deliver) values (270469, 47, 'Esch');
insert into track_num (track_num, order_id, address_to_deliver) values (625018, 4, 'Dayton');
insert into track_num (track_num, order_id, address_to_deliver) values (314898, 62, 'Browning');
insert into track_num (track_num, order_id, address_to_deliver) values (262707, 3, 'Ryan');
insert into track_num (track_num, order_id, address_to_deliver) values (252643, 38, 'Carberry');
insert into track_num (track_num, order_id, address_to_deliver) values (765094, 52, 'Shoshone');
insert into track_num (track_num, order_id, address_to_deliver) values (683861, 42, 'Continental');
insert into track_num (track_num, order_id, address_to_deliver) values (579475, 17, 'Longview');
insert into track_num (track_num, order_id, address_to_deliver) values (674528, 3, 'Orin');
insert into track_num (track_num, order_id, address_to_deliver) values (230846, 14, 'Bartillon');
insert into track_num (track_num, order_id, address_to_deliver) values (427678, 21, 'Corry');
insert into track_num (track_num, order_id, address_to_deliver) values (677128, 12, 'Buena Vista');
insert into track_num (track_num, order_id, address_to_deliver) values (874483, 76, 'Russell');
insert into track_num (track_num, order_id, address_to_deliver) values (253269, 81, 'Rockefeller');
insert into track_num (track_num, order_id, address_to_deliver) values (331238, 65, 'Fairfield');
